const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      brand: 'Nike',
      image: '/images/p1.jpg',
      price: 110,
      rating: 4.5,
      numReviews: 10,
      description: 'Slim Fit formal Shirt',
      countInStock: 20,
    },
    {
      _id: '2',
      name: 'Levis Regular Shirt',
      category: 'Shirts',
      brand: 'Levis',
      image: '/images/p2.jpg',
      price: 130,
      rating: 4.2,
      numReviews: 15,
      description: 'Regular formal Shirt',
      countInStock: 11,
    },
    {
      _id: '3',
      name: 'Peter England Slim Shirt',
      category: 'Shirts',
      brand: 'Peter England',
      image: '/images/p3.jpg',
      price: 150,
      rating: 4.7,
      numReviews: 20,
      description: 'Regular fit formal Shirt',
      countInStock: 7,
    },
    {
      _id: '4',
      name: 'Levis Plain Pants',
      category: 'Pants',
      brand: 'Levis',
      image: '/images/p4.jpg',
      price: 120,
      rating: 4,
      numReviews: 12,
      description: 'Slim Fit White Pants',
      countInStock: 5,
    },
    {
      _id: '5',
      name: 'Pavilion Pants',
      category: 'Pants',
      brand: 'Pavilion',
      image: '/images/p5.jpg',
      price: 100,
      rating: 4.1,
      numReviews: 10,
      description: 'Gray fit pants',
      countInStock: 10,
    },
    {
      _id: '6',
      name: 'Flu Gray Pants',
      category: 'Shirts',
      brand: 'Flu',
      image: '/images/p6.jpg',
      price: 150,
      rating: 3.5,
      numReviews: 20,
      description: 'Slim Fit formal Pants',
      countInStock: 0,
    },
  ],
}

export default data
